### ISSUE TITLE
Expose both $inuit-heading-size-x and $inuit-heading-height-x

### ISSUE THREAD

**Issue by jzempel** [inuitcss/base.headings#3]
...so I can take advantage of both parameters of the `inuit-font-size` mixin. So add something like

```
$inuit-heading-height-1:  auto !default;
.
.
$inuit-heading-height-6:  auto !default;
```

and use those variables in the mixin calls.

**Comment by csswizardry** [comment]
With this partial being so small, if you want that level of control I would just suggest copying/pasting the contents of `_base.headings.scss` and creating your own, passing in exactly what you wish (and making responsive, etc.).
