### ISSUE TITLE
bower version not release on Github

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/base.headings#5]
Same issue as [settings.defaults #4](https://github.com/inuitcss/settings.defaults/issues/4)
Last bower version of `inuit-headings` is 0.3.1 but last Github release is `0.3.0`, can you fix it ?

**Comment by florianbouvot** [comment]
@csswizardry and @anselmh, can you fix this issue ?

**Comment by florianbouvot** [comment]
Thank you @anselmh

**Comment by anselmh** [comment]
You’re welcome. Pushed the tag now. Therefore Closing.
